spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/bezpieczenstwo
        username: postgres
        password: 1
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true

config:
    secret: topsecret